export const CONSUMER_ADD_REQUEST = "consumer/CONSUMER_ADD_REQUEST";
export const CONSUMER_ADD_SUCCESS = "consumer/CONSUMER_ADD_SUCCESS";
export const CONSUMER_ADD_FAIL = "consumer/CONSUMER_ADD_FAIL";

export const GET_CONSUMER_LIST_REQUEST = "consumer/GET_CONSUMER_LIST_REQUEST";
export const GET_CONSUMER_LIST_SUCCESS = "consumer/GET_CONSUMER_LIST_SUCCESS";
export const GET_CONSUMER_LIST_FAIL = "consumer/GET_CONSUMER_LIST_FAIL";

export const CREATE_PREVIEW_REQUEST = "consumer/CREATE_PREVIEW_REQUEST";
export const CREATE_PREVIEW_SUCCESS = "consumer/CREATE_PREVIEW_SUCCESS";
export const CREATE_PREVIEW_FAIL = "consumer/CREATE_PREVIEW_FAIL";

export const PREVIEW_LIST_REQUEST = "consumer/PREVIEW_LIST_REQUEST";
export const PREVIEW_LIST_SUCCESS = "consumer/PREVIEW_LIST_SUCCESS";
export const PREVIEW_LIST_FAIL = "consumer/PREVIEW_LIST_FAIL";

export const LATEST_PREVIEW_REQUEST = "consumer/LATEST_PREVIEW_REQUEST";
export const LATEST_PREVIEW_SUCCESS = "consumer/LATEST_PREVIEW_SUCCESS";
export const LATEST_PREVIEW_FAIL = "consumer/LATEST_PREVIEW_FAIL";

export const UPDATE_PREVIEW_REQUEST = "consumer/UPDATE_PREVIEW_REQUEST";
export const UPDATE_PREVIEW_SUCCESS = "consumer/UPDATE_PREVIEW_SUCCESS";
export const UPDATE_PREVIEW_FAIL = "consumer/UPDATE_PREVIEW_FAIL";

export const DELETE_PREVIEW_REQUEST = "consumer/DELETE_PREVIEW_REQUEST";
export const DELETE_PREVIEW_SUCCESS = "consumer/DELETE_PREVIEW_SUCCESS";
export const DELETE_PREVIEW_FAIL = "consumer/DELETE_PREVIEW_FAIL";

export const DOWNLOAD_PREVIEW_REQUEST = "consumer/DOWNLOAD_PREVIEW_REQUEST";
export const DOWNLOAD_PREVIEW_SUCCESS = "consumer/DOWNLOAD_PREVIEW_SUCCESS";
export const DOWNLOAD_PREVIEW_FAIL = "consumer/DOWNLOAD_PREVIEW_FAIL";
